name: "GTools"
on:
  workflow_dispatch:
    # 手动触发

jobs:
  package:
    strategy:
      matrix: # [windows-2019, macos-11, ubuntu-latest]
        platform: [macos-11]
        go-version: [1.19.2]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      # - name: install MinGW
      #   if: matrix.platform == 'windows-2019'
      #   uses: egor-tensin/setup-mingw@v2
      #   with: 
      #     platform: x64
      # - name: Setup MSYS2
      #   if: matrix.platform == 'windows-2019'
      #   uses: msys2/setup-msys2@v2
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build GTools for Windows-amd64
        if: matrix.platform == 'windows-2019'
        run: |
          wails build -clean -tags exp_gowebview2loader
      - name: Build GTools for MacOS-amd64
        if: matrix.platform == 'macos-11'
        run: |
          wails build -clean
      - name: upload artifacts macOS
        if: matrix.platform == 'macos-11'
        uses: actions/upload-artifact@v3
        with:
          name: GTools-macos-amd64
          path: build/bin/*
      - name: upload artifacts windows
        if: matrix.platform == 'windows-2019'
        uses: actions/upload-artifact@v3
        with:
          name: GTools-windows-amd64
          path: build/bin/*
      - name: upload artifacts ubuntu
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: GTools-linux-amd64
          path: build/bin/*
